### ISSUE TITLE
Bug: core dumped after entering cotp password - cotp v1.2.2

### ISSUE THREAD

**Issue by Libre4IT** [replydev/cotp#188] opened 2023-02-23 11:02 UTC
After entering the cotp password, the following error message appears:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "DecodeError { position: 26, kind: Symbol }"', src/interface/table.rs:73:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

Tested with cotp-bin v1.2.2-1 on Arch linux: https://aur.archlinux.org/cotp-bin.git

Reference:
https://github.com/replydev/cotp/blob/d789c6159eff5a1afa26968f482596419f443f18/src/interface/table.rs#L73

**Comment by replydev** [comment] 2023-02-26 18:09
Thank you for reporting, can you send me some steps to replicate the exact case?

**Comment by Libre4IT** [comment] 2023-02-27 21:42
No additional information is provided after running `RUST_BACKTRACE=1 cotp`
This is the result when doing a  `RUST_BACKTRACE=full cotp`
Password: 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "DecodeError { position: 26, kind: Symbol }"', src/interface/table.rs:73:36
stack backtrace:
   0:     0x5655334eb2e0 - <unknown>
   1:     0x56553344e0fe - <unknown>
   2:     0x5655334c2274 - <unknown>
   3:     0x5655334ec82f - <unknown>
   4:     0x5655334ec42f - <unknown>
   5:     0x5655334ed4a2 - <unknown>
   6:     0x5655334ecf84 - <unknown>
   7:     0x5655334eceec - <unknown>
   8:     0x5655334ecec1 - <unknown>
   9:     0x5655333ce5e2 - <unknown>
  10:     0x5655333cea12 - <unknown>
  11:     0x565533405cc6 - <unknown>
  12:     0x56553340c533 - <unknown>
  13:     0x565533409265 - <unknown>
  14:     0x5655333d83fd - <unknown>
  15:     0x56553341034e - <unknown>
  16:     0x7f85d12da790 - <unknown>
  17:     0x7f85d12da84a - __libc_start_main
  18:     0x5655333d4b8e - <unknown>
  19:                0x0 - <unknown>
Aborted (core dumped)

**Comment by replydev** [comment] 2023-02-28 16:30
Ok thank, you i forgot that the debug info is striped out from the release binary.

When i get some time i will release a fix for this.

Probably you have an OTP secret that is not encoded correctly (or not handled correctly by the software), so i will prevent the UI to crash and highlight OTP codes with possible problems.

Thank you again for reporting.

**Comment by replydev** [comment] 2023-02-28 20:24
@Libre4IT could you try this branch, UI should not crash anymore but highlight errors: #192

**Comment by Libre4IT** [comment] 2023-02-28 20:50
@replydev when cloning the repo and do a git branch I only see the master. Would you be able to assist?

**Comment by replydev** [comment] 2023-02-28 20:59
Of course, please do:

- `git fetch -a` to fetch all the repository metadata.
- `git checkout -b fix/crash_on_decode origin/fix/crash_on_decode` to checkout the branch.
- `cargo run` to run the software.

To replicate the test case you could export your database using `cotp export` and then import in the development project using `cargo run -- import -c -p <path_of_exported_file.json>`.

**Comment by Libre4IT** [comment] 2023-02-28 22:00
It's fixed now. Great work!

**Comment by replydev** [comment] 2023-02-28 22:07
Closing the issue as the problem is solved, feel free to open another issue if you think that the highlighted code (the one that gave the error) is right.

**Closed by replydev** 2023-02-28 22:07 UTC
Labels: bug
