### ISSUE TITLE
`cotp import --otp-uri --path [file]` doesn't seem to work

### ISSUE THREAD

**Issue by brian6932** [replydev/cotp#424] opened 2024-05-03 01:34 UTC
Mentioned in https://github.com/replydev/cotp/issues/157#issuecomment-2062952310.
```zsh
❯ cotp import --otp-uri --path test.txt
Password:

An error occurred: expected value at line 1 column 1

❯ cotp --version
cotp 1.6.0

❯ cargo install --list | rg cotp
cotp v1.6.0 (https://github.com/replydev/cotp#adc54fdc):
    cotp.exe
```

**Comment by replydev** [comment] 2024-05-05 14:10
Duplicate of #423

**Closed by replydev** 2024-05-05 14:10 UTC

**Comment by brian6932** [comment] 2024-05-05 18:36
This isn't a duplicate @replydev this is a different issue.
